-- This table lists rollercoasters in the United States with its thrill rating, opening year and park included.

CREATE TABLE "112FARROS"."XCOASTER"
( "COAST_NUM" NUMBER NOT NULL ENABLE,
"COAST_NAME" VARCHAR2(40 BYTE), "RATING" VARCHAR2(20 BYTE), "OPEN_DATE" NUMBER, "PARK_NUM" NUMBER,
CONSTRAINT "PK_CNUM" PRIMARY KEY ("COAST_NUM") TABLESPACE "USERS" ) ENABLE,
CONSTRAINT "FK_PNUM" FOREIGN KEY ("PARK_NUM") REFERENCES "112FARROS"."XPARK" ("PARK_NUM") ENABLE
) SEGMENT CREATION IMMEDIATE;