-- This table joins each park with any events from the Events table that it hosts.

CREATE TABLE "112FARROS"."XHASEVENT"
( "PARK_NUM" NUMBER NOT NULL ENABLE,
"EVENT_NUM" NUMBER NOT NULL ENABLE,
CONSTRAINT "PK_EPNUM" PRIMARY KEY ("PARK_NUM", "EVENT_NUM")
TABLESPACE "USERS" ) ENABLE,
CONSTRAINT "FK_EVENT" FOREIGN KEY ("EVENT_NUM")
REFERENCES "112FARROS"."XEVENT" ("EVENT_NUM") ENABLE, CONSTRAINT "FK_PARK" FOREIGN KEY ("PARK_NUM")
REFERENCES "112FARROS"."XPARK" ("PARK_NUM") ENABLE ) SEGMENT CREATION IMMEDIATE;