-- This table joins parks with awards they may have won.

CREATE TABLE "112FARROS"."XRECEIVES"
( "PARK_NUM" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"AWARD_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
CONSTRAINT "PK_RECS" PRIMARY KEY ("PARK_NUM", "AWARD_ID")