-- In some instances, a park may decide to close and sell one of it’s rollercoasters to another park. This table 
-- tracks each coaster that has been relocated in the database along its current and former parks, and the year it was relocated.
CREATE TABLE "112FARROS"."XRELOCATEDFROM" ( "RELOC_ID" NUMBER NOT NULL ENABLE,
"COAST_NUM" NUMBER, "PARENT_NUM" NUMBER, "CHILD_NUM" NUMBER, "RELOC_YEAR" NUMBER,
CONSTRAINT "PK_RELOCID" PRIMARY KEY ("RELOC_ID") TABLESPACE "USERS" ) ENABLE,
CONSTRAINT "FK_COASTER" FOREIGN KEY ("COAST_NUM") REFERENCES "112FARROS"."XCOASTER" ("COAST_NUM") ENABLE,
CONSTRAINT "FK_PARENT" FOREIGN KEY ("PARENT_NUM") REFERENCES "112FARROS"."XPARK" ("PARK_NUM") ENABLE,
CONSTRAINT "FK_CHILD" FOREIGN KEY ("CHILD_NUM") REFERENCES "112FARROS"."XPARK" ("PARK_NUM") ENABLE
) SEGMENT CREATION IMMEDIATE